---
- name: Extra vars vault
  hosts: localhost

  vars_files:
          - vars/oscreds.yml

  tasks:
          - name: print out encrypted vars
            debug:
                    msg: "{{ imscloud }}"

